#!/bin/sh

# Time-stamp: <2013-04-09 11:32:17 Tuesday by lzy>

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# language settings
#export LANG=zh_CN.UTF-8
export LC_CTYPE=zh_CN.UTF-8

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

# input settings
if [ -x /usr/bin/scim ] || [ -x /usr/local/bin/scim ]; then
    export XMODIFIERS="@im=SCIM"
    export XIM=SCIM
    export XIM_PROGRAM=scim
    export GTK_IM_MODULE=scim
    export QT_IM_MODULE=scim
    scim -d
fi

if [ -x /usr/bin/nm-applet ] || [ -x /usr/local/bin/nm-applet ]; then
    nm-applet --sm-disable&
fi

if [ -x /usr/bin/wallpaper.sh ]; then
    wallpaper.sh&
fi

trayer --edge top --align right --SetDockType true --expand true --width 7 --transparent true --tint 0x000000 --alpha 0 --height 18&
# set the cursor
xsetroot -cursor_name left_ptr
# start xmonad
exec ck-launch-session dbus-launch xmonad
