#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#export LANG=zh_CN.UTF-8
export LC_CTYPE=zh_CN.UTF-8

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

export XMODIFIERS="@im=SCIM"
export XIM=SCIM
export XIM_PROGRAM=scim
export GTK_IM_MODULE=scim
export QT_IM_MODULE=scim
scim -d

nm-applet --sm-disable&
./.wallpaper.sh&

trayer --edge top --align right --SetDockType true --expand true --width 8 --transparent true --tint 0x000000 --alpha 0 --height 19&
# set the cursor
xsetroot -cursor_name left_ptr
# start xmonad
exec ck-launch-session dbus-launch xmonad
